server:
  port: 8080
logging:  level:     org.springframework.amqp: DEBUG 
#spring:
#  profiles:#    active:#    - default
spring:
  application:    name: customer
  datasource:
    username: 'learntocode'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'learntocode'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:      ddl-auto: update
    show-sql: true
  zipkin:
        base-url:  http://localhost:9411
  rabbitmq:
        addresses: localhost:5672        cache:          connection:                  mode: channel
        
eureka:  client:    service-url:       defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false             
    