server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'learntocode'
    url: jdbc:postgresql://postgres:5432/customer
    password: 'learntocode'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
        base-url: http://zipkin:9411
  rabbitmq:
        addresses: rabbitmq:5672
        cache:
          connection:
                  mode: channel
        
eureka:
  client:
    service-url:
       defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false             
