server:
  port: 8081
  
spring:
  application:
    name: fraud
  datasource:
    username: 'learntocode'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'learntocode'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
      base-url:  http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true